#!/bin/bash

CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_3/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_3/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_3/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_4/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_4/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(4) Cardiomyopathies diseases/folds/fold_4/test.csv"


CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_0/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_0/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_0/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_1/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_1/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_1/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_2/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_2/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_2/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_3/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_3/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_3/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_4/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_4/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(5) Dysrhythmias diseases/folds/fold_4/test.csv"


CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_0/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_0/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_0/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_1/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_1/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_1/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_2/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_2/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_2/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_3/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_3/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_3/test.csv"
CUDA_VISIBLE_DEVICES=2 python3 run.py --config MIMIC/config.json --train-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_4/train.csv" --val-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_4/val.csv" --test-csv "/data/wolf6245/src/AutoPrognosis-Multimodal/data_mimic/(6) Heart failure/folds/fold_4/test.csv"